# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

TourArtwork.destroy_all
Tour.destroy_all
Artwork.destroy_all
User.destroy_all

a1 = Artwork.create(title: "Bridging Home", artist: "Do Ho Suh", year: 2018, lat: 51.516259, lng: -0.082591, address: "28 Wormwood St, London EC2M 1RP, UK", description: "Do Ho Suh's new installation at Wormwood Street, EC2, commissioned by Art Night and Sculpture in the City, is on view until 2020. Bridging Home, London is a replica of a traditional Korean house and surrounding bamboo garden, which will appear to have 'fallen' onto the Wormwood Street footbridge. Suh's first large-scale outdoor installation in the capital, the work reflects the artist's own experience of moving across continents and between cultures, and continues his career-long investigation of memory, migration, the multiplicity of the immigrant experience, and home as both a physical structure and a lived experience."),
a2 = Artwork.create(title: "Winged Figure", artist: "Barbara Hepworth", year: 1963, lat: 51.5150151, lng: -0.1465281, address: "318 Oxford St, Marylebone, London W1C 1HF, UK", description: "Winged Figure by Barbara Hepworth, erected 1963. The work was founded by Morris Singer, Walthamstow, and is mounted on the east elevation of the John Lewis Oxford Street store, facing onto the south end of Holles Street. The materials are aluminium alloy with stainless steel rods. Winged Figure is a concave form of two wing-like projections of unequal height, joined in the middle. The wings curve outwards away from the building on the vertical axis, and curve in towards each other at the top and bottom. Both wings are pierced with an irregularly-shaped hole. Fine steel rods connect the wings diagonally at opposing points along their outer edge, an arrangement which creates a sense of twisting movement and flow."),
a3 = Artwork.create(title: "Quantum Cloud", artist: "Antony Gormley", year: 1999, lat: 51.5018406, lng: 0.0012875, address: "Meridian Gate, Greenwich, London SE10 0AX, UK", description: "How can you convey the fact that the presence of somebody is greater or different from their appearance? The Quantum Clouds sculptures continue Gormley's exploration into the outer space of the body through the continuation of the branching connections, positioning the original body-field within a wider field. The indeterminacy of the skin summons active involvement of the projection and finding force in the eye of the beholder. It is an open question in the Quantum Clouds sculptures - whether the body is emerging from a chaotic energy field, or the field from the body."),
a4 = Artwork.create(title: "Fulcrum", artist: "Richard Serra", year: 1987, lat: 51.5182884, lng: -0.0837733, address: "15 Eldon St, London EC2M 2AB, UK", description: "Commissioned to create a large sculpture for a small space, artist Richard Serra designed upwards. At 55 feet high, Fulcrum is comprised of five trapezoidal plates of weatherproof steel which prop against each other to form a self-supporting sculpture of architectural proportions. Serra’s interest in industrial materials goes back to childhood when his father worked as a pipefitter at a San Francisco shipyard. Later, during the 1950s, Serra worked in steel mills to support his college education. Best known for steel sculptures that engage audiences through material, form and site specificity, Serra encourages viewers to experience spatial and physical interplay between Fulcrum and its surrounding architecture and prompts re-evaluation of physicality, one’s movement and movement of others within a given built environment. Located at the heart of Broadgate’s busy pedestrian realm in the City of London, the public is free to approach Fulcrum from all angles and enter inside."),
a5 = Artwork.create(title: "Nelson's Ship in a Bottle", artist: "Yinka Shonibare", year: 2010, lat: 51.4800943, lng: -0.008517, address: "10 Stockwell St, Greenwich, London SE10 9BD, UK", description: "This work is a scaled-down replica of HMS Victory, the ship captained by Nelson. It was commissioned by the Greater London Authority in 2009 for the fourth plinth in Trafalgar Square, where it was displayed from May 2010 to January 2012. The only significant departure from the historical Victory is the use of richly patterned Dutch Wax fabric (a trademark of Shonibare's work) for the 37 sails. The fabric is commonly associated with African dress and symbolic of African identity and independence. Tying together historical and global threads, the work considers the legacy of British colonialism and its expansion in trade and Empire, made possible through the freedom of the seas and new trade routes that Nelson's victory provided."),
a6 = Artwork.create(title: "Traffic Light Tree", artist: "Pierre Vivant", year: 1998, lat: 51.5068188, lng: -0.0105748, address: "5TG, Trafalgar Way, London, United Kingdom", description: "Once located in the junctions of Westferry Road, Heron Quay Bank and Marsh Wall, this traffic light mutation was moved to Billingsgate Market. This eight-metre-tall stoplight 'tree' changes its 75 sets of lights in a random order, no doubt much to the confusion of unprepared drivers. Designed by artist Pierre Vivant in 1998, the changing patterns of the 'Traffic Light Tree' were meant to reflect the 'never ending rhythm of the surrounding domestic, financial and commercial activities'."),
a7 = Artwork.create(title: "Newton After Blake", artist: "Eduardo Paolozzi", year: 1995, lat: 51.5254808, lng: -0.1347529, address: "Euston Square Station, Euston Rd, Bloomsbury, London NW1 2BN, UK", description: "This sculpture is based on William Blake's 1795 print of Newton, Personification of Man Limited by Reason, which depicts a naked Isaac Newton sitting on ledge beside a mossy rock face while measuring with a pair of compasses or dividers. The print was intended by Blake to criticise Newton's profane knowledge, usurping the sacred knowledge and power of the creator Urizen, with the scientist turning away from nature to focus on his books. Paolozzi had admired Blake since viewing a large print of Newton at the Tate Gallery in the 1940s. The sculpture includes Paolozzi's self-portrait as the naked Newton, measuring the universe with his dividers. The eyes were copied from Michelangelo's David. It can be interpreted as symbolising a confluence of the two cultures, the arts and the sciences, and illustrating how Newton changed our view of the world to one determined by mathematical laws."),
a8 = Artwork.create(title: "Ventilation Shaft Cover", artist: "Eduardo Paolozzi", year: 1982, lat: 51.4880612, lng: -0.1352689, address: "22 St.George's Square, Pimlico, London SW1V 2HP, UK", description: "The Ventilation Shaft Cover was commissioned from Paolozzi by the Crown Estate Commissioners through Whitfield Partners who, between 1976 and 1983, designed and constructed two commercial blocks to either side of the piece. The sculpture was designed and produced between 1978-82, and cast by the Robert Taylor Foundry in Larbert, Scotland. In addition to adorning the public realm created by the immediate architectural scheme, the sculpture may have a functional role screening a ventilation shaft for an underground car park, but although suggested in some references, it has no functional relationship with London Underground."),
a9 = Artwork.create(title: "The Arch", artist: "Henry Moore", year: 1979, lat: 51.5076578, lng: -0.1754371, address: "Unnamed Road, London W2 3XA, UK", description: "The Arch is a six-metre high Roman travertine sculpture positioned on the north bank of the Long Water. It was presented by the artist Henry Moore to the nation for siting in Kensington Gardens in 1980 - two years after his eightieth-birthday exhibition at the Serpentine Gallery, London. The Arch is made from seven travertine stones weighing a total of 37 tonnes. The stones were sourced from a quarry in northern Italy."),
a10 = Artwork.create(title: "Physical Energy", artist: "George Frederic Watts", year: 1907, lat: 51.506769, lng: -0.1805402, address: "Budge's Walk, London W2 3HJ, UK", description: "Watts had very high ideals for his art, and intended his work to help humanity embrace progress. Physical Energy is an allegory of the human need for new challenges – of our instinct to always be scanning the horizon, looking towards the future. In the artist’s own words, it is ‘a symbol of that restless physical impulse to seek the still unachieved in the domain of material things’."),
a11 = Artwork.create(title: "Wind Sculpture", artist: "Yinka Shonibare", year: 2014, lat: 51.4967558, lng: -0.1393183, address: "145 Victoria St, Westminster, London SW1E 5NH, UK", description: "Wind Sculpture, a site specific commision, is permanently displayed as part of Howick Place in Victoria, London. Measuring 6 metres by 3 metres, the work explores the notion of harnessing movement, through the idea of capturing and freezing a volume of wind in a moment in time."),
a12 = Artwork.create(title: "Three Perpetual Chords", artist: "Conrad Shawcross", year: 2015, lat: 51.4453742, lng: -0.0797747, address: "Unnamed Road, Dulwich, London SE21 7EB, UK", description: "This sculptural installation was commissioned by Southwark Council as a legacy to the sculpture that was stolen from the park in 2011, Two Forms, Divided Circle, by Barbara Hepworth. Three Perpetual Chords draws from the artist’s ongoing study of harmonics and represents The Octave, The Fifth and The Fourth within the western harmonic scale. The work forms a trail in the northern end of the park, with each piece just visible from the last, resting lightly on the grass and emphasising the contrast between the industrial material and its natural environment."),
a13 = Artwork.create(title: "Single Form", artist: "Barbara Hepworth", year: 1961, lat: 51.4773572, lng: -0.1550437, address: "Carriage Dr S, Battersea, London SW11, UK", description: "Single Form (Memorial), a fully abstract piece by British sculptor Dame Barbara Hepworth, is one of three iterations of this work. It was used as the model for developing her most prestigious international commission, by the Jacob and Hilda Blaustein Foundation, of a 6.5m high Single Form (Memorial to Dag Hammarskjöld), which stands outside the United Nations Secretariat building in New York. Hammarskjöld, a friend of Hepworth's, died in a plane crash in Zambia en route to a peace mission to the Congo on 18 September 1961. She explains to her biographer 'when I heard of his death, in a kind of despair, I made the ten-foot high Single Form (Memorial). Memorial was made just to console myself, because I was so upset'."),
a14 = Artwork.create(title: "The Burghers of Calais", artist: "Auguste Rodin", year: 1985, lat: 51.4974849, lng: -0.1270897, address: "14 Great College St, Westminster, London SW1P 3RX, UK", description: "The Burghers of Calais by the French sculptor Auguste Rodin, represents the idea of freedom from oppression. It tells the story of the siege of Calais in 1347, during the Hundred Years War. Calais had been surrounded for a year by English soldiers under King Edward III. The Burghers, six leading citizens of Calais, offered to die if Edward spared the rest of the town's people. Edward's wife, Queen Philippa, heard about the Burgher's offer and asked if they could also be spared if the town surrendered. Edward agreed and all the people of Calais were allowed to leave. Rodin made his original sculpture in 1889 to stand outside Calais town hall and later made four casts, of which this is one."),
a15 = Artwork.create(title: "Eros", artist: "Sir Alfred Gilbert", year: 1893, lat: 51.5099007, lng: -0.1366672, address: "Piccadilly Circus (Stop F), Soho, London W1B 5RW, UK", description: "The Shaftesbury Memorial Fountain, also known as 'Eros', is a fountain surmounted by a winged statue of Anteros, located at the southeastern side of Piccadilly Circus. Moved after World War II from its original position in the centre, it was erected in 1892–1893 to commemorate the philanthropic works of famous Victorian politician and philanthropist Anthony Ashley Cooper, 7th Earl of Shaftesbury, and his achievement in replacing child-labour with school education. The fountain overlooks the south-west end of Shaftesbury Avenue, also named for the Earl."),
a16 = Artwork.create(title: "Girl with a Dolphin Fountain", artist: "David Wynne", year: 1973, lat: 51.5062443, lng: -0.0737342, address: "St. Katharine Pier, United Kingdom", description: "David Wynn’s statue is a picture of movement. It is elegantly created to show a diving girl playing with an inquisitive dolphin, their meeting frozen perfectly in time. You can easily imagine them below the waves in the warm sea of some far away place."),
a17 = Artwork.create(title: "World Turned Upside Down", artist: "Mark Wallinger", year: 2019, lat: 51.5144143, lng: -0.1195387, address: "20 Kean St, Holborn, London WC2B, UK", description: "The World Turned Upside Down is a large political globe, four metres in diameter, with nation states and borders outlined but with the simple and revolutionary twist of being inverted. Most of the landmasses now lie in the ‘bottom’ hemisphere with the countries and cities re-labelled for this new orientation. What becomes clear at this scale, and on a globe rather than the flat, rectangular Mercator projection we are used to seeing, is the proper scale of Africa in comparison with the other continents, and the vastness of the oceans. Mark Wallinger, artist, said: 'The UN is the authority as to the names and borders. This is the world, as we know it from a different viewpoint. Familiar, strange, and subject to change.'"),
a18 = Artwork.create(title: "A Bullet from a Shooting Star", artist: "Alex Chinneck", year: 2015, lat: 51.5013462, lng: -0.0005957, address: "Tunnel Ave, Greenwich, London SE10 0AX, UK", description: "British sculptor Alex Chinneck is renowned for elevating everyday objects and scenarios to surreal monuments, transforming the familiar into the extraordinary. For London Design Festival 2015, he created A Bullet from a Shooting Star, an outdoor installation at Greenwich Peninsula that was testament to the site’s rich industrial history and acted as a visual beacon during the day and night, signifying the site’s future as a new residential district for London. The enormous lattice of steel took the form of an inverted electricity pylon that appeared to have been shot into the ground at a precarious angle. The site-specific installation played with the industrial language of the peninsula, which was once home to the largest oil and gas works in Europe and a steelworks. The work’s construction and materiality reflected that of the historical structures still on site, particularly that of the now-abandoned gas tower."),
a19 = Artwork.create(title: "ArcelorMittal Orbit", artist: "Anish Kapoor", year: 2012, lat: 51.5384281, lng: -0.0129014, address: "5 Thornton St, London E20 2AD, UK", description: "Designed by sculptor Sir Anish Kapoor and engineer Cecil Balmond, the ArcelorMittal Orbit is one of the most striking and enduring visual legacies of the London 2012 Olympic and Paralympic Games. 60% of the ArcelorMittal Orbit is made from recycled steel, including washing machines and used cars."),
a20 = Artwork.create(title: "Paternoster Vents", artist: "Thomas Heatherwick", year: 2002, lat: 51.5142984, lng: -0.1004411, address: "5 Ave Maria Ln, London EC4M 7AQ, UK",description: "These massive stainless steel sculptural artworks near St Paul’s Cathedral are both art and function – for they are also ventilation shafts for an electricity substation in the basement underneath. Created by Heatherwick Studio who split the ventilation into three separate units. Two, the massive steel vents are quite obvious, and by splitting them into two it created a more interesting space for the rest of the square. The third is harder to spot, but of equal necessity — the air intakes, and if you wander around the square, you’ll find grills in the floor. These are the “hidden in plain sight” air intakes, which suck cool air down, to be heated and then vented away by the artwork."),
a21 = Artwork.create(title: "Nail", artist: "Gavin Turk", year: 2011, lat: 51.5137917, lng: -0.0962698, address: "36 New Change London EC4M 9AG New Change, London EC4M 9AG, UK", description: "Both comic and provocative, Nail is a 12 metre bronze sculpture, treated as the title implies, to appear like a giant rusty nail. Standing at the entrance French architect, Jean Paul Nouvel’s shiny glass shopping centre, One New Change with the grand sixteenth century architecture of St Paul’s cathedral in the background, Nail is hammered between the ancient and modern. At the intersection of these two worlds, Nail is a nostalgic recollection of tools traditionally used by the construction industry and favoured by Turk’s archetypal white van man, now of less and less necessity in the modern architecture of One New Change. Its rustiness, meanwhile underscores the uselessness of this once useful object, while also suggesting the creep of the natural into the territory of the man-made. Not only a literal object, the nail doubles as a psychological object which suggests “nail in the coffin” and “nailed to the cross.” Rather more humorously, viewed from a certain angle, Nail appears to pin One New Change into the ground, although viewed from other angles, it hints at the empty space where what was nailed has long since been removed. A giant magnification of a miniature object, the closer the viewer stands to Nail, the more comically abstract the object appears, as by contrast, both the viewer and its surroundings appear to shrink."),
a22 = Artwork.create(title: "Taxi", artist: "John Seward Johnson II", year: 1983, lat: 51.5111924, lng: -0.1062229, address: "2 John Carpenter St, London EC4Y 0AP, UK", description: "Taxi was formerly sited on Park Avenue and 47th Street New York, USA before being moved to London in 2014. The artist, John Seward Johnson II is an American artist known for his trompe l'oeil painted bronze statues. His life-size bronze statues are castings of living people, depicting them engaged in day-to-day activities."),
a23 = Artwork.create(title: "Resolution", artist: "Antony Gormley", year: 2007, lat: 51.5155896, lng: -0.1062929, address: "18-76 Shoe Ln, London EC4A 3JB, UK", description: "In the words of the artist; 'Seen from afar it looks like a man, from close up it looks like a city. It is wonderful to be able to site a work that interacts with the daily life of the street'."),
a24 = Artwork.create(title: "Forgotten Streams", artist: "Cristina Iglesias", year: 2017, lat: 51.5119704, lng: -0.0910004, address: "22 Bloomberg Arcade, London EC4N 5AG, UK", description: "This revelatory landscape installation cast in bronze is woven through three different plaza spaces, evoking the Lost Rivers of London, namely the Walbrook. While obviously a metaphorical interpretation, the proximity to the actual route (not exact but close) to the Walbrook activates the historical ecology of place."),
a25 = Artwork.create(title: "Slice of Reality", artist: "Richard Wilson", year: 2000, lat: 51.5041547, lng: -0.0003111, address: "2 Waterview Dr, Greenwich, London SE10 0TX, UK", description: "Standing on the foreshore of the Thames, the work comprises of a sliced vertical section of an ocean going sand dredger. The original ship was reduced in length by 85%, leaving a vertical portion housing the ships habitable sections: bridge, poop, accommodation and engine room. The slicing of the vessel opened the structure, leaving it exposed to the effects of weather and tide."),
a26 = Artwork.create(title: "Large Spindle Piece", artist: "Henry Moore", year: 1974, lat: 51.530695, lng: -0.125576, address: "King’s Cross Square, Kings Cross, London N1C 4AL, UK", description: "The sculpture was inspired by a flint pebble Moore picked up in the fields around his home at Perry Green in Hertfordshire. He pressed it into a lump of clay, and then cast it, eventually having it scaled up into several versions."),
a27 = Artwork.create(title: "The Meeting Place", artist: "Paul Day", year: 2007, lat: 51.5300122, lng: -0.1253313, address: "St Pancras International, Euston Rd, Kings Cross, London N1C 4QP, UK", description: "The reunited embracing couple under a clock at a railway station is something that can be universally recognised as a symbol of travel. The clock becomes a moon at night. There is a sense of reunification and romance. The terracotta draft frieze beneath the couple depicts 'dream-like' scenes inspired by the railways, including a Tube train driven by a skeleton as a bearded drunk sways precariously close to the passing train. Another shows the attempted suicide of a jilted lover under a train reflected in the sunglasses of a fellow passenger. Another section reveals a woman in a short skirt with her legs wrapped round her lover while they wait for the next train. Other less controversial parts of the frieze depict soldiers leaving on troop trains for the First World War and the evacuation of London's underground network after the terror attacks of 7 July 2005."),
a28 = Artwork.create(title: "Witness", artist: "Antony Gormley", year: 2011, lat: 51.529882, lng: -0.129804, address: "96 Euston Rd, Kings Cross, London NW1 2DB", description: "Witness, was commissioned by English PEN to mark their 90th anniversary and has been placed permanently at the British Library. Cast in iron, the work depicts an empty chair, a symbol that English PEN has used for the last 30 years to represent imprisoned writers around the world."),
a29 = Artwork.create(title: "Planets", artist: "Antony Gormley", year: 2002, lat: 51.5299996, lng: -0.1297279, address: "60 Chalton St, Kings Cross, London NW1 1HS, UK", description: "This sculpture is made up of eight granite glacial erratics, each inscribed with a different body silhouette. Gormley wanted to reverse Michelangelo's slaves, where a quarried square rock had to conform to the represented body. In Planets, the outline of the body conforms to the stone, suggesting a dependency. The outline was carved to an adequate depth, where the form was beginning to be self-revealed, so is on the cusp between a drawing and the arising of self-determined form."),
a30 = Artwork.create(title: "St Joan", artist: "Keith Gran", year: 1971, lat: 51.5290594, lng: -0.1279481, address: "40 Ossulston St, Kings Cross, London NW1 1JJ, UK", description: "This sculpture is inspired by George Bernard Shaw’s play Saint Joan and was designed as the symbol of the Shaw Theatre. Its component parts are the abstract forms of a knight’s helmet and the long bows and lances of medieval armies. The work commemorates events in Joan’s life but also the courage of subsequent women victims of oppression and injustice. George Bernard Shaw lived in St Pancras where he was a Vestryman of the Parish."),
a31 = Artwork.create(title: "Piscator", artist: "Eduardo Paolozzi", year: 1980, lat: 51.5272423, lng: -0.135475, address: "65 Cobourg St, Kings Cross, London NW1 2HH, UK", description: "This is arguably the least recognisable Paolozzi sculpture in London. It sits outside Euston station and nobody seems to know who is responsible for looking after it. Following the privatization of the network, the Eduardo Paolozzi Foundation has been struggling to ascertain who’s the current actual owner of the piece, and demand it be restored. The sculpture itself displays a mixture of organic and mechanical elements, in an homage to the German Expressionist and theatre director Erwin Piscator."),
a32 = Artwork.create(title: "Pecking Bird", artist: "Gary Hume", year: 2013, lat: 51.5252173, lng: -0.140695, address: "4 Triton Square, London NW1 3HG, UK", description: "Hume’s first public artwork in his bold painting style is over forty feet tall and consists of twenty aluminum panels joined together in a single towering composition. Birds and other motifs from the natural world pervade Hume’s work, and Pecking Bird particularly evokes the avian wildlife of Regent’s Park, a 275-acre parkland near Regent’s Place."),
a33 = Artwork.create(title: "Reflection", artist: "Antony Gormley", year: 2001, lat: 51.5241933, lng: -0.1418338, address: "Regent's Place, 350 Euston Rd, London NW1 3AX, United Kingdom", description: "Cast in iron from his own body, Antony Gormley’s ‘Reflection’ has the patina of actual skin and is life size. The two figures, located opposite each other inside and outside 350 Euston Road, deliberately play with perception and trick our senses. ‘Reflection’ offers a moment of peace and quiet, and is a poignant expression of Gormley’s quest for identity."),
a34 = Artwork.create(title: "Chromorama", artist: "David Batchelor", year: 2015, lat: 51.5197922, lng: -0.0858633, address: "29 Wilson St, Finsbury, London EC2M 2SJ, UK", description: "Since the early 1990s, David Batchelor has been working with integrating vivid colour and often large-scale sculptural work. This 20-metre stack of 35 illuminated steel boxes faces in all directions and acts as a beacon at the intersection of several streets and pedestrian pathways."),
a35 = Artwork.create(title: "Square The Block", artist: "Richard Wilson", year: 2009, lat: 51.5150047, lng: -0.118416, address: "New Academic Building, Holborn, London WC2A 3LJ, UK", description: "At the corner of Kingsway and Sardinia Street stands a vertical manufactured corner of a building located in the space offset marginally from the chamfered end wall. The sculptures two edges we’re copied from two chosen vertical areas on the existing buildings two sides, but when placed together made no architectural and functional sense other than matching the cornice work and completing the corner. The base section appears compressed and twisted as if shunted upwards to free up the walkway."),
a36 = Artwork.create(title: "Locking Piece", artist: "Henry Moore", year: 1964, lat: 51.4902351, lng: -0.1297672, address: "23 John Islip St, Westminster, London SW1P 4ED, UK", description: "Locking Piece comprises two interlocking forms holding a third element between them, on a bronze base. The work has an organic form that defies description, with different amorphous shapes visible from different angles. It has a central hole, where the top piece rises over the bottom piece; at one end, the two larger elements are separated by a third smaller disc-like element, like a piece of cartilage. Moore gave different accounts of the inspiration for the sculpture: it may reflect his observations of two pebbles that unexpectedly interlocked, or of a sawn bone fragment with a joint. The lower piece may be developed from a vertebra."),
a37 = Artwork.create(title: "Eye-I", artist: "Bruce McLean", year: 1993, lat: 51.5199979, lng: -0.08135, address: "Sun St Passage, Hackney, London, UK", description: "Look once, look twice and you’ll realise Bruce McLean’s artwork forms the outline of a female face. Eye-I links to this iconic stretch of East London thanks to the artist’s use of steel (the material used in the surrounding buildings)."),
a38 = Artwork.create(title: "City Wing", artist: "Christopher le Brun", year: 2009, lat: 51.5143794, lng: -0.0884146, address: "Bank of England, London, UK", description: "This sculpture takes the form of an inclined wing, constructed from bronze, rising from the plaza. The wing is several storeys high and Expedition worked alongside Morris Singer bronze foundry to design and construct the stainless steel support system to connect this 10m cantilever to the base, concealed below the paving."),
a39 = Artwork.create(title: "Time and Tide", artist: "Simon Patterson", year: 2004, lat: 51.5108559, lng: -0.0846383, address: "17 Eastcheap, London EC3M 1BU, UK", description: "The theme of Time and Tide is a reference to the long and varied history of the City and of the moon's constant influence on the tides of the Thames which ebb and flow endlessly over time. To express this, Patterson created two distinct elements; Time and Tide. The Time element is represented by a series of textual lists embedding into the pavement which follow a gentle arc along the passageway, charting events, people, places and institutions related to the City's past and present. The lists are playful to follow as they alternate in orientation for each row, and some are incomplete as they are abruptly truncated when they meet the walls of adjacent buildings or the end of the lane itself. The Tide element is represented by a 41m long by 6m tall illuminated panel depicting a photograph of the surface of the moon. The colour of the illumination varies slowly over time and is a dramatic spectacle especially at dusk when the lit panel casts its coloured light over the passageway and surrounding walls of Plantation Place, and if raining also reflecting off the wet floor."),
a40 = Artwork.create(title: "HSBC Gates", artist: "Anthony Caro", year: 2000, lat: 51.5119233, lng: -0.0983694, address: "105 Queen Victoria St, London EC4V 4EH, UK", description: "These unusual sculptures by Anthony Caro assisted by Gavin Morris stand on the north side of the Millennium Bridge. The design of both pairs is related. They consist of a rectangular steel tunnel with a narrow and a wide end, surmounted by a narrower rectangular tunnel. The larger internal space at the bottom, opens into the narrower space above. They are made from shot-blasted stainless steel."),
a41 = Artwork.create(title: "Vortex", artist: "Barbara Sandler", year: 1999, lat: 51.5202248, lng: -0.0752646, address: "12 Lamb St, Spitalfields, London E1 6EA, UK", description: "Vortex was created by Barbara Sandler at the behest of St George PLC, a development company. From one side it looks entirely abstract but from another side seems to represent a crouching man."),
a42 = Artwork.create(title: "Rush Hour", artist: "George Segal", year: 1987, lat: 51.5192554, lng: -0.0850844, address: "1-2 Finsbury Ave, London EC2M 2PP, UK", description: "A highly experimental and innovative artist, Pop Art pioneer Segal was renowned for casting his figures directly from life – usually friends and family – using plaster bandages to create human scale moulds from which his bronze sculptures could be cast. In Rush Hour, Segal captures a group of city dwellers to perfection, each one going about their daily routine in a highly life-like manner. We’ve all been there..."),
a43 = Artwork.create(title: "Wooden Boat with Seven People", artist: "Kalliopi Lemos", year: 2011, lat: 51.5202987, lng: -0.0774625, address: "30 Spital Square, Spitalfields, London E1 6DX, UK", description: "Wooden Boat with Seven People features an authentic boat that was used to transport refugees from Turkey to the shores of the Greek Islands. The sculptural installation aims to reflect Spitalfields’ rich history of providing shelter for successive waves of migrants across the centuries."),
a44 = Artwork.create(title: "Allies", artist: "Lawrence Holofcener", year: 1995, lat: 51.5097319, lng: -0.1440207, address: "Hong Kong Economic & Trade Office, 6 Grafton St, Mayfair, London W1S 4EQ, UK", description: "Bronze sculpture celebrating the relationship between Churchill and Roosevelt. The two friends sit on a bench talking amiably, with Churchill holding his trademark cigar. Princess Margaret unveiled the statue on May 2, 1995, to commemorate fifty years of peace."),
a45 = Artwork.create(title: "I Goat", artist: "Kenny Hunter", year: 2011, lat: 51.5190794, lng: -0.0800935, address: "4 Exchange Arcade, Spitalfields, London EC2M 3WA, UK", description: "I Goat was inspired by Spitalfields’ rich and ongoing social history. ‘Goats are associated with non-conformity and being independently-minded. That is also true of London, its people and never more so than in Spitalfields’ said the artist at the official sculpture unveiling."),
a46 = Artwork.create(title: "William Blake Mosaics", artist: "Southbank Mosaics", year: 2001, lat: 51.4993233, lng: -0.1144514, address: "216 Carlisle Ln, South Bank, London SE1 7LH, UK", description: "The trio of arches beside Archbishop's Park are decorated with mosaics inspired by William Blake. Dozens of works line the walls of Carlisle Lane, Virgil Street and Centaur Street. Some recreate Blake's visionary art, others repeat lines of his poetry, some present both, all on or near the site of his former home. Blake lived with his wife Catherine on Hercules Road from 1790 to 1800. The mosaics were pieced together over many years by local volunteers, under the guidance of Southbank Mosaics."),
a47 = Artwork.create(title: "Seven Noses of Soho", artist: "Rick Buckley", year: 1997, lat: 51.5133947, lng: -0.1325371, address: "68 Dean St, Soho, London W1D 4QJ, UK", description: "An artist called Rick Buckley was ‘unmasked’ by the Evening Standard in 2011 and claimed he installed these noses as a snub against CCTV spying culture in London, seeing it as an infringement of liberty. Mostly though, he just wanted to see if he could get away with glueing 35 noses across London. There’s thought to be seven noses left in Soho, at; Admiralty Arch, Bateman Street, Dean Street, Meard Street (pictured), Endell Street, Great Windmill Street and D’Arbly Street. The story goes that to find them all brings infinite wealth."),
a48 = Artwork.create(title: "Crystal Palace Dinosaurs", artist: "Benjamin Waterhouse Hawkins", year: 1854, lat: 51.4175376, lng: -0.0673189, address: "13 Orchard Grove, London SE20 8DN, UK", description: "These ‘dinosaur’ statues actually refer to approximately 30 palaeontological statues around the tidal lake in Crystal Palace Park. The statues represent the first ever attempt anywhere in the world to model extinct animals as full-scale, three-dimensional, active creatures from fossil remains. The sculptor, Benjamin Waterhouse Hawkins was a natural history illustrator and sculptor of international reputation. Some of the statues are wildly inaccurate compared with modern interpretations. Who decided what they should look like is a subject of historical debate. However, research by historians shows clearly that experts in the 1850s had different interpretations, and these differences in view are reflected in the statues on display. The story of these evolving interpretations demonstrates how scientific ideas evolve when new evidence and ideas comes to light."),
a49 = Artwork.create(title: "Two Piece Reclining Figure No 3", artist: "Henry Moore", year: 1961, lat: 51.4825164, lng: -0.1040682, address: "23 Royal Rd, London SE17 3NN, UK", description: "Bronze from carved plaster cast; early eight feet long on plinth, set on grassy mound. A reclining figure of two halves, from Moore's first series to explore the relationship between elements thus disjointed, and based on studies of bones and flints. Its carved, rugged and naturalistic quality is well suited to its urban setting."),
a50 = Artwork.create(title: "A Conversation with Oscar Wilde", artist: "Maggi Hambling", year: 1998, lat: 51.5087658,lng: -0.1281489, address: "2 St. Martin's Pl, Charing Cross, London WC2H 0NN, UK", description: "This work by artist Maggi Hambling was chosen as a memorial to Oscar Wilde. The work is inscribed with a quotation from Wilde’s play Lady Windermere’s Fan: ‘We are all in the gutter but some of us are looking at the stars’. The sculpture is bench-like green granite sarcophagus, with a bust of Wilde emerging from the upper end, with a hand holding a cigarette."),

user1 = User.create(username: "Bob1", email: "bob@bob.com", password: "password000")

tour1 = Tour.create(name: "Sculpture Vultures", user_id: User.all.map {|user| user.id}.sample )
tour2 = Tour.create(name: "Art in the City", user_id: User.all.map {|user| user.id}.sample )

ta1 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta2 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta3 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta4 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta5 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta6 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta7 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta8 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta9 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)
ta10 = TourArtwork.create(tour_id: Tour.all.map {|tour| tour.id}.sample, artwork_id: Artwork.all.map {|artwork| artwork.id}.sample)


puts "---------------------seeded-----------------------"